---
- name: Enable UFW Firewall on Ubuntu
  hosts: all
  become: true
  tasks:
    - name: Install UFW if not already installed
      apt:
        name: ufw
        state: present
        update_cache: yes

    - name: Allow SSH
      ufw:
        rule: allow
        port: 22
        proto: tcp

    - name: Enable UFW
      ufw:
        state: enabled
        logging: on

    - name: Ensure UFW is enabled and active
      command: ufw status
      register: ufw_status

    - name: Debug UFW status
      debug:
        msg: "{{ ufw_status.stdout }}"
