---
- name: Enable UFW firewall on Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Install UFW if not present
      ansible.builtin.apt:
        name: ufw
        state: present
      when: ansible_os_family == "Debian"

    - name: Enable UFW firewall
      ansible.builtin.command: ufw --force enable
      when: ansible_os_family == "Debian"

    - name: Allow incoming SSH connections
      ansible.builtin.command: ufw allow ssh
      when: ansible_os_family == "Debian"

    - name: Reload UFW to apply changes
      ansible.builtin.command: ufw reload
      when: ansible_os_family == "Debian"
