---
- name: Enable or Disable Firewall on Ubuntu
  hosts: all
  become: yes
  vars:
    firewall_state: "enable"  # เปลี่ยนเป็น "disable" ถ้าต้องการปิด firewall

  tasks:
    - name: Check if UFW is installed
      apt:
        name: ufw
        state: present
      register: ufw_installed

    - name: Enable Firewall
      command: ufw enable
      when: firewall_state == "enable"
      notify: reload_firewall

    - name: Disable Firewall
      command: ufw disable
      when: firewall_state == "disable"
      notify: reload_firewall

  handlers:
    - name: reload_firewall
      command: ufw reload
      when: firewall_state == "enable"
