---
- name: Enable UFW Firewall on Ubuntu
  hosts: all
  become: true
  tasks:
    - name: Ensure UFW is installed
      ansible.builtin.apt:
        name: ufw
        state: present

    - name: Enable UFW Firewall
      ansible.builtin.command:
        cmd: ufw enable
      register: enable_firewall_result

    - name: Start UFW Service
      ansible.builtin.service:
        name: ufw
        state: started

    - name: Enable UFW Service to start on boot
      ansible.builtin.systemd:
        name: ufw
        enabled: true

    - name: Check UFW Service Status
      ansible.builtin.command:
        cmd: systemctl status ufw
      register: ufw_service_status
      changed_when: false
      failed_when: "'inactive (dead)' not in ufw_service_status.stdout"

    - name: Debug - Show UFW Service Status
      ansible.builtin.debug:
        msg: "{{ ufw_service_status.stdout }}"
